version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rilispro
    container_name: rilispro
    restart: unless-stopped
    working_dir: /var/www/rilispro
    volumes:
      - ./:/var/www/rilispro
      - ./storage/php.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "9000:80"
    networks:
      - rilispro

  webserver:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/rilispro
      - ./storage/:/etc/nginx/conf.d
    networks:
      - rilispro

  db:
    image: mysql:5.7
    container_name: dbrilispromysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: rilispro
      MYSQL_ROOT_PASSWORD: artha
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - rilispro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_rilispro
    tty: true
    restart: always
    ports: 
      - 7000:80
    networks:
      - rilispro
    depends_on:
      - db

networks:
  rilispro:
    driver: bridge

volumes:
  dbdata:
    driver: local
